### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by mark-hahn** [turbobabr/easyeda-extension-menu-ux-normalizer#4]
I may be doing something wrong but it doesn't seem to work for me.  After installing I see this ...

![Screenshot (934)](https://user-images.githubusercontent.com/811455/187047550-c3a7d765-4ae3-4073-8c54-37f0d96d9c66.png)

Then when I reboot the menus still open when hovering.

easyeda version 6.5.14
chrome stable latest version

**Comment by turbobabr** [comment]
@mark-hahn , are you sure you installed the extension correctly? According to your screenshot, you installed it as a `script`, but it should be installed as an extension. 

Please follow the step listed in the `Installation` section or checkout a short screencast demonstrating an installation process for other extension:
- https://github.com/turbobabr/easyeda-ibom-extension#installation

**Comment by mark-hahn** [comment]
Thanks, that worked.  When I did the installation I just selected the js file.  You should put that video on your page.  :-)
